/*
Source: Edabit
Link : https://edabit.com/challenge/iLKzMSTSuRmYByxwA
Date: 06/29/2021

Coloured Triangles
=====================

A coloured triangle is created from different rows of colours (Red, Green or Blue). Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If colours are different, the missing colour is used in the new row. This process continues untill a single colour is generated in the final row.

Different possibilities of colours are:

Colours Touching:        G G        B G        R G        B R
New colour:               G          R          B          G
With a bigger example:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
Goal
Create a function which takes first row of the triangle as an input and returns the final colour which would appear at the bottom row. In above example, given input "RRGBRGBB" will return "G".
If you are only given one colour as the input, return that colour.
There will be no exception handling case.
Examples
colouredTriangle("B") ? "B"

colouredTriangle("GB") ? "R"

colouredTriangle("RBRGBRB") ? "G"
Notes
N/A
*/
#include<iostream>
#include<vector>
#include<cmath>
using namespace std;
/*
char colouredTriangle(string r) {
  if(r.size()==1) return r[0];
  string r1="";
  char ans=0;
  for(int i=0;i<r.size()-1;i++){
    if(r[i]==r[i+1]) ans=r[i];
    else if(r[i]=='B' && r[i+1]=='G' || r[i]=='G' && r[i+1]=='B') ans='R';
    else if(r[i]=='B' && r[i+1]=='R' || r[i]=='R' && r[i+1]=='B') ans='G';
    else if(r[i]=='R' && r[i+1]=='G' || r[i]=='G' && r[i+1]=='R') ans='B';
    r1+=ans;
  }
  return colouredTriangle(r1);
}
*/

using namespace std;
char colouredTriangle(string r) {
	if(r.size()==1) return r[0];
	string r1="";
	char ans=0;
	for(int i=0;i<r.size()-1;i++){
		if(r[i]==r[i+1]) ans=r[i];
		else ans= 'G' + 'B' + 'R' - r[i]-r[i+1];
		r1+=ans;
	}
  return colouredTriangle(r1);
}


int main(){
	cout << colouredTriangle("B")   << endl;
	cout << colouredTriangle("GB") << endl;	
	cout << colouredTriangle("RBRGBRB") << endl;		
	return 0;
}

/*

Online Compiler : https://replit.com/languages/cpp?v2=1

colouredTriangle("B") ? "B"

colouredTriangle("GB") ? "R"

colouredTriangle("RBRGBRB") ? "G"
Notes

*/
